namespace DotNet.Cli;

/// <summary>
///     Represents the result of "dotnet" command execution.
/// </summary>
public interface ICommandResult
{
    /// <summary>
    ///     Gets a value indicating whether "dotnet" command execution was successful.
    /// </summary>
    bool IsSuccess { get; }

    /// <summary>
    ///     Gets the standard output generated by "dotnet" command execution.
    /// </summary>
    string Output { get; }

    /// <summary>
    ///     Gets the error output generated by "dotnet" command execution.
    /// </summary>
    string Error { get; }
}