global using System.Diagnostics;
global using System.IO.Abstractions;
global using System.Linq;
global using System.Text;
global using DotNetWhy.Core;
global using DotNetWhy.Core.Models;
global using DotNetWhy.Services;
global using DotNetWhy.Validators;
global using Microsoft.Extensions.DependencyInjection;