namespace DotNet.Cli.Commands;

/// <summary>
///     Represents the result of "dotnet" command execution.
/// </summary>
internal sealed class CommandResult(
    bool isSuccess,
    string output,
    string error)
    : ICommandResult
{
    /// <summary>
    ///     Gets a value indicating whether "dotnet" command execution was successful.
    /// </summary>
    public bool IsSuccess { get; } = isSuccess;

    /// <summary>
    ///     Gets the standard output generated by "dotnet" command execution.
    /// </summary>
    public string Output { get; } = output;

    /// <summary>
    ///     Gets the error output generated by "dotnet" command execution.
    /// </summary>
    public string Error { get; } = error;

    internal static CommandResult Success(string output) =>
        new(
            true,
            output,
            CommandResultDefaults.Output);

    internal static CommandResult Failure(string error, string output = null) =>
        new(
            false,
            output ?? CommandResultDefaults.Output,
            error);
}